#!/usr/bin/env node
// scripts/build.mjs
//
// Phase 6 production build. Run via `npm run build` (wired below) or
// directly as the Netlify/Vercel build command: `node scripts/build.mjs`.
//
// What it does:
//   1. Reads the Firebase web config from environment variables (see
//      .env.example for the exact names) and writes a real
//      src/firebase/firebase-config.js into a temp copy of src/ (the
//      checked-in firebase-config.js stays a git-ignored placeholder —
//      this script never writes secrets back into the repo).
//   2. Bundles + minifies everything under src/ and copies public/ as-is
//      into dist/, which is the directory Netlify/Vercel should serve.
//
// Required env vars (set these in Netlify/Vercel's dashboard, never in
// git):
//   FIREBASE_API_KEY
//   FIREBASE_AUTH_DOMAIN
//   FIREBASE_PROJECT_ID
//   FIREBASE_STORAGE_BUCKET
//   FIREBASE_MESSAGING_SENDER_ID
//   FIREBASE_APP_ID
//
// Netlify: Site settings → Build & deploy → Build command: `node scripts/build.mjs`
//          Publish directory: `dist`
// Vercel:  Project settings → Build Command: `node scripts/build.mjs`
//          Output Directory: `dist`

import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import path from "node:path";
import fs from "node:fs/promises";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const srcDir = path.join(rootDir, "src");
const publicDir = path.join(rootDir, "public");
const distDir = path.join(rootDir, "dist");
const tmpSrcDir = path.join(rootDir, ".build-src-tmp");

const REQUIRED_ENV_VARS = [
  "FIREBASE_API_KEY",
  "FIREBASE_AUTH_DOMAIN",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID",
];

async function main() {
  assertEnvVars();

  await fs.rm(distDir, { recursive: true, force: true });
  await fs.rm(tmpSrcDir, { recursive: true, force: true });

  // 1. Copy src/ into a temp dir, then overwrite firebase-config.js with the
  //    real values from env — the git-ignored source file never changes.
  await fs.cp(srcDir, tmpSrcDir, { recursive: true });
  await fs.writeFile(
    path.join(tmpSrcDir, "firebase", "firebase-config.js"),
    generateFirebaseConfig()
  );

  // 2. Copy public/ (assets, robots.txt, HTML shells) straight into dist/.
  await fs.cp(publicDir, distDir, { recursive: true });

  // 3. Bundle + minify each HTML entry's module script(s) referenced from
  //    public/index.html and public/login.html. main.js is the single
  //    bootstrap entry per the Phase 1 decision to use one entry point.
  await build({
    entryPoints: [path.join(tmpSrcDir, "main.js")],
    bundle: true,
    minify: true,
    sourcemap: false,
    format: "esm",
    outfile: path.join(distDir, "assets", "main.bundle.js"),
    target: ["es2020"],
  });

  // 4. Copy component/global CSS into dist so <link> tags in the HTML
  //    shells continue to resolve (build.mjs does not rewrite HTML — it
  //    assumes public/index.html and public/login.html already reference
  //    /assets/main.bundle.js and the CSS files under their original
  //    src/styles paths, mirrored below).
  await fs.cp(path.join(tmpSrcDir, "styles"), path.join(distDir, "styles"), {
    recursive: true,
  });

  await fs.rm(tmpSrcDir, { recursive: true, force: true });

  console.log(`Build complete → ${path.relative(rootDir, distDir)}/`);
}

function assertEnvVars() {
  const missing = REQUIRED_ENV_VARS.filter((key) => !process.env[key]);
  if (missing.length) {
    console.error(
      `Missing required environment variable(s): ${missing.join(", ")}\n` +
        `Set these in your Netlify/Vercel project settings before building.`
    );
    process.exit(1);
  }
}

function generateFirebaseConfig() {
  return `// Auto-generated by scripts/build.mjs at build time from environment
// variables. Do not edit directly or commit this file's real values.
export const firebaseConfig = {
  apiKey: "${process.env.FIREBASE_API_KEY}",
  authDomain: "${process.env.FIREBASE_AUTH_DOMAIN}",
  projectId: "${process.env.FIREBASE_PROJECT_ID}",
  storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${process.env.FIREBASE_APP_ID}",
};
`;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
